package main

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/mcpdev80/baseharbor/internal/application"
	bhruntime "github.com/mcpdev80/baseharbor/internal/runtime"
)

const workloadPortOverridesFile = "workload-ports.env"

var (
	composePublishedPortVariableRE = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*):-([0-9]{1,5})\}\s*:`)
	conflictingHostPortRE          = regexp.MustCompile(`(?i)(?:127\.0\.0\.1:|0\.0\.0\.0:|\[::\]:|host port\s+)([0-9]{1,5})`)
)

type workloadPublishedPortVariable struct {
	Name        string
	DefaultPort int
}

func mergePersistedWorkloadPortOverrides(environment map[string]string, files application.RuntimeFiles) error {
	path := filepath.Join(files.Dir, workloadPortOverridesFile)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read workload port overrides: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, value, ok := strings.Cut(line, "=")
		if !ok || !validWorkloadEnvironmentName(name) {
			return fmt.Errorf("invalid workload port override entry %q", line)
		}
		if _, explicit := os.LookupEnv(name); explicit {
			continue
		}
		if _, err := parsePort(value); err != nil {
			return fmt.Errorf("invalid persisted workload port override %s=%s: %w", name, value, err)
		}
		environment[name] = value
	}
	return nil
}

func persistWorkloadPortOverride(files application.RuntimeFiles, environment map[string]string, name string, port int) error {
	if err := os.MkdirAll(files.Dir, 0o700); err != nil {
		return err
	}
	overrides := map[string]string{}
	path := filepath.Join(files.Dir, workloadPortOverridesFile)
	if data, err := os.ReadFile(path); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			key, value, ok := strings.Cut(line, "=")
			if ok {
				overrides[key] = value
			}
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	overrides[name] = strconv.Itoa(port)
	keys := make([]string, 0, len(overrides))
	for key := range overrides {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by BaseHarbor. Repository environment variables set explicitly by the operator take precedence.\n")
	for _, key := range keys {
		fmt.Fprintf(&builder, "%s=%s\n", key, overrides[key])
	}
	if err := os.WriteFile(path, []byte(builder.String()), 0o600); err != nil {
		return err
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return err
	}
	environment[name] = strconv.Itoa(port)
	return nil
}

func workloadPublishedPortVariables(workload application.WorkloadFiles) ([]workloadPublishedPortVariable, error) {
	data, err := os.ReadFile(workload.Compose)
	if err != nil {
		return nil, err
	}
	seen := map[string]struct{}{}
	result := []workloadPublishedPortVariable{}
	for _, match := range composePublishedPortVariableRE.FindAllStringSubmatch(string(data), -1) {
		port, err := strconv.Atoi(match[2])
		if err != nil || port < 1 || port > 65535 {
			continue
		}
		if _, ok := seen[match[1]]; ok {
			continue
		}
		seen[match[1]] = struct{}{}
		result = append(result, workloadPublishedPortVariable{Name: match[1], DefaultPort: port})
	}
	return result, nil
}

func conflictingWorkloadHostPort(err error) int {
	if err == nil {
		return 0
	}
	match := conflictingHostPortRE.FindStringSubmatch(err.Error())
	if len(match) != 2 {
		return 0
	}
	port, _ := strconv.Atoi(match[1])
	return port
}

func currentWorkloadPort(variable workloadPublishedPortVariable, environment map[string]string) int {
	if value, ok := environment[variable.Name]; ok {
		if port, err := strconv.Atoi(value); err == nil {
			return port
		}
	}
	if value, ok := os.LookupEnv(variable.Name); ok {
		if port, err := strconv.Atoi(value); err == nil {
			return port
		}
	}
	return variable.DefaultPort
}

func proposedWorkloadPort(conflict int) int {
	start := conflict + 1
	switch conflict {
	case 80:
		start = 8080
	case 443:
		start = 8443
	}
	return firstAvailablePort(start)
}

func commandAssumesYes() bool {
	for _, arg := range os.Args[1:] {
		if arg == "--yes" || arg == "-y" {
			return true
		}
	}
	return false
}

func acceptWorkloadPortFallback(in io.Reader, out io.Writer, variable string, from, to int) (bool, error) {
	fmt.Fprintf(out, "Workload host port %d is already in use.\n", from)
	fmt.Fprintf(out, "Found free host port %d for %s.\n", to, variable)
	if commandAssumesYes() || !readerIsTerminal(in) {
		fmt.Fprintf(out, "[RETRY] using %s=%d automatically.\n", variable, to)
		return true, nil
	}
	fmt.Fprintf(out, "Use %d instead? [Y/n]: ", to)
	answer, err := bufio.NewReader(in).ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return false, err
	}
	answer = strings.TrimSpace(strings.ToLower(answer))
	if answer == "" || answer == "y" || answer == "yes" || answer == "j" || answer == "ja" {
		return true, nil
	}
	return false, nil
}

func startRepositoryWorkloadWithPortFallback(ctx context.Context, in io.Reader, out io.Writer, compose bhruntime.Compose, workload application.WorkloadFiles, files application.RuntimeFiles, environment map[string]string, startServices, composeFiles []string) error {
	variables, err := workloadPublishedPortVariables(workload)
	if err != nil {
		return fmt.Errorf("inspect application workload published ports: %w", err)
	}
	const maxAttempts = 4
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		err := compose.UpProjectFilesSelected(ctx, workload.Project, workload.RepositoryRoot, environment, startServices, composeFiles...)
		if err == nil {
			return nil
		}
		if !bhruntime.IsPortBindingConflict(err) || attempt == maxAttempts {
			return err
		}
		conflict := conflictingWorkloadHostPort(err)
		if conflict == 0 {
			return err
		}
		var candidate *workloadPublishedPortVariable
		for i := range variables {
			if currentWorkloadPort(variables[i], environment) == conflict {
				candidate = &variables[i]
				break
			}
		}
		if candidate == nil {
			return fmt.Errorf("%w; conflicting published port %d is not backed by a configurable ${VAR:-PORT} Compose binding", err, conflict)
		}
		if _, explicit := os.LookupEnv(candidate.Name); explicit {
			return fmt.Errorf("%w; %s=%d was set explicitly by the operator, choose another free value and retry", err, candidate.Name, conflict)
		}
		fallback := proposedWorkloadPort(conflict)
		if fallback == 0 {
			return fmt.Errorf("%w; no free fallback port found for %s", err, candidate.Name)
		}
		accepted, promptErr := acceptWorkloadPortFallback(in, out, candidate.Name, conflict, fallback)
		if promptErr != nil {
			return promptErr
		}
		if !accepted {
			return fmt.Errorf("workload port fallback declined for %s; choose a free host port and retry", candidate.Name)
		}
		if downErr := compose.DownProjectFilesEnv(ctx, workload.Project, workload.RepositoryRoot, environment, composeFiles...); downErr != nil {
			return errors.Join(err, fmt.Errorf("clean up partially started workload before host-port retry: %w", downErr))
		}
		if persistErr := persistWorkloadPortOverride(files, environment, candidate.Name, fallback); persistErr != nil {
			return errors.Join(err, fmt.Errorf("persist workload host-port fallback: %w", persistErr))
		}
	}
	return errors.New("application workload start exhausted host-port retries")
}
