package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/mcpdev80/baseharbor/internal/application"
	"github.com/mcpdev80/baseharbor/internal/cli"
)

func appEnvCommand(store application.Store) *cli.Command {
	return &cli.Command{
		Name:    "env",
		Summary: "Show the standard environment contract for an application",
		Usage:   "baha app env NAME [--format dotenv|shell|json|yaml] [--reveal] [--path]",
		Long:    "Shows the native runtime contract generated by 'baha app apply'. Values that contain service credentials are masked by default. --reveal prints the real values. --path prints only the owner-only dotenv file path so IDEs and normal application tooling can load it directly. No BaseHarbor SDK or runtime login is required by the application.",
		Run: func(ctx context.Context, args []string, out, errOut io.Writer) error {
			name, format, reveal, pathOnly, err := parseAppEnvArgs(args)
			if err != nil {
				return err
			}
			m, _, err := store.Load(name)
			if err != nil {
				return err
			}
			files, err := application.ExistingRuntimeFiles(store, m)
			if err != nil {
				return err
			}
			if _, err := os.Stat(files.ApplicationEnv); err != nil {
				if os.IsNotExist(err) {
					return fmt.Errorf("application runtime contract is not materialized; run 'baha app apply %s'", name)
				}
				return fmt.Errorf("inspect application environment contract: %w", err)
			}
			if pathOnly {
				fmt.Fprintln(out, files.ApplicationEnv)
				return nil
			}
			values, err := loadApplicationEnv(files.ApplicationEnv)
			if err != nil {
				return err
			}
			if !reveal {
				maskRuntimeSecrets(values)
			}
			return writeApplicationEnv(out, values, format)
		},
	}
}

func parseAppEnvArgs(args []string) (name, format string, reveal, pathOnly bool, err error) {
	format = "dotenv"
	for i := 0; i < len(args); i++ {
		switch arg := args[i]; {
		case arg == "--reveal":
			reveal = true
		case arg == "--path":
			pathOnly = true
		case arg == "--format":
			if i+1 >= len(args) {
				return "", "", false, false, usageError("--format requires a value", "Use dotenv, shell, json or yaml.")
			}
			i++
			format = args[i]
		case strings.HasPrefix(arg, "--format="):
			format = strings.TrimPrefix(arg, "--format=")
		case strings.HasPrefix(arg, "-"):
			return "", "", false, false, usageError("unknown option "+arg, "Run 'baha app env --help' for available options.")
		default:
			if name != "" {
				return "", "", false, false, usageError("baha app env accepts exactly one NAME", "Example: baha app env demo")
			}
			name = arg
		}
	}
	if name == "" {
		return "", "", false, false, usageError("baha app env requires NAME", "Example: baha app env demo")
	}
	if pathOnly && reveal {
		return "", "", false, false, usageError("--path and --reveal cannot be combined", "Use --path to load the protected file directly or --reveal to print values.")
	}
	switch format {
	case "dotenv", "shell", "json", "yaml":
	default:
		return "", "", false, false, usageError("unsupported --format "+format, "Use dotenv, shell, json or yaml.")
	}
	return name, format, reveal, pathOnly, nil
}

func loadApplicationEnv(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read application environment contract: %w", err)
	}
	values := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || key == "" {
			return nil, fmt.Errorf("application environment contract contains an invalid entry")
		}
		values[key] = value
	}
	return values, nil
}

func maskRuntimeSecrets(values map[string]string) {
	for _, key := range []string{"DATABASE_URL", "REDIS_URL", "VALKEY_URL"} {
		if values[key] != "" {
			values[key] = "<masked>"
		}
	}
}

func writeApplicationEnv(out io.Writer, values map[string]string, format string) error {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	switch format {
	case "dotenv":
		for _, key := range keys {
			fmt.Fprintf(out, "%s=%s\n", key, values[key])
		}
	case "shell":
		for _, key := range keys {
			fmt.Fprintf(out, "export %s=%s\n", key, strconv.Quote(values[key]))
		}
	case "json":
		encoded, err := json.MarshalIndent(values, "", "  ")
		if err != nil {
			return err
		}
		encoded = append(encoded, '\n')
		_, err = out.Write(encoded)
		return err
	case "yaml":
		for _, key := range keys {
			fmt.Fprintf(out, "%s: %s\n", key, strconv.Quote(values[key]))
		}
	}
	return nil
}
