#!/usr/bin/env bash
set -euo pipefail

out_dir="${1:-ci-evidence}"
title="${2:-BaseHarbor CI Evidence}"
phase="${3:-ci}"
ref="${4:-${GITHUB_REF_NAME:-unknown}}"
sha="${5:-${GITHUB_SHA:-unknown}}"
rows_file="${6:-}"

mkdir -p "$out_dir"

escape_html() {
  sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

status_badge() {
  case "$1" in
    success|passed|pass) printf '%s' 'PASS' ;;
    failure|failed|fail) printf '%s' 'FAIL' ;;
    skipped) printf '%s' 'SKIP' ;;
    cancelled|canceled) printf '%s' 'CANCEL' ;;
    *) printf '%s' "$1" ;;
  esac
}

run_url=""
if [ -n "${GITHUB_SERVER_URL:-}" ] && [ -n "${GITHUB_REPOSITORY:-}" ] && [ -n "${GITHUB_RUN_ID:-}" ]; then
  run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
fi

{
  echo "# $title"
  echo
  echo "| Field | Value |"
  echo "| --- | --- |"
  echo "| Phase | `$phase` |"
  echo "| Repository | `${GITHUB_REPOSITORY:-unknown}` |"
  echo "| Ref | `$ref` |"
  echo "| Commit | `$sha` |"
  echo "| Run | `${GITHUB_RUN_ID:-unknown}` |"
  echo "| Attempt | `${GITHUB_RUN_ATTEMPT:-1}` |"
  echo "| Generated | `$(date -u +'%Y-%m-%dT%H:%M:%SZ')` |"
  if [ -n "$run_url" ]; then
    echo "| GitHub Actions | $run_url |"
  fi
  echo
  echo "## Test results"
  echo
  echo "| Check | Result | Evidence |"
  echo "| --- | --- | --- |"
  if [ -n "$rows_file" ] && [ -f "$rows_file" ]; then
    while IFS=$'\t' read -r check status detail || [ -n "${check:-}" ]; do
      [ -n "${check:-}" ] || continue
      badge="$(status_badge "${status:-unknown}")"
      detail="${detail:-}"
      printf '| %s | **%s** | %s |\n' "$check" "$badge" "$detail"
    done < "$rows_file"
  fi
} > "$out_dir/summary.md"

{
  cat <<'EOF'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BaseHarbor CI Evidence</title>
<style>
:root{color-scheme:dark;background:#07111f;color:#e8f0fb;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
body{margin:0;background:radial-gradient(circle at top left,#153047 0,#07111f 42%,#040a12 100%);min-height:100vh}
main{max-width:1100px;margin:0 auto;padding:48px 28px 72px}
header{padding:28px;border:1px solid #23405c;border-radius:18px;background:rgba(8,22,37,.86);box-shadow:0 18px 50px rgba(0,0,0,.25)}
h1{margin:0 0 8px;font-size:30px;letter-spacing:-.02em}
.subtitle{color:#9fb4c8;margin:0}
.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin-top:22px}
.meta div{padding:12px 14px;border-radius:12px;background:#0c1b2a;border:1px solid #1d3348}
.meta b{display:block;color:#86a6c3;font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}
code{color:#d9ecff;overflow-wrap:anywhere}
section{margin-top:24px;padding:24px;border:1px solid #203a53;border-radius:18px;background:rgba(7,19,32,.9)}
table{width:100%;border-collapse:collapse}
th,td{text-align:left;padding:13px 12px;border-bottom:1px solid #1b3248;vertical-align:top}
th{color:#8fb2cf;font-size:12px;text-transform:uppercase;letter-spacing:.08em}
.badge{display:inline-block;padding:4px 9px;border-radius:999px;font-weight:700;font-size:12px;letter-spacing:.04em}
.pass{background:#123b2c;color:#9cf3c4;border:1px solid #276b50}
.fail{background:#471f28;color:#ffb4bd;border:1px solid #7d3543}
.skip{background:#3a3421;color:#f4dda0;border:1px solid #685d34}
.cancel{background:#382846;color:#ddb6ff;border:1px solid #614078}
.unknown{background:#273544;color:#c4d5e6;border:1px solid #41566b}
footer{color:#718aa0;margin-top:18px;font-size:12px}
a{color:#7cc7ff}
</style>
</head>
<body><main>
EOF
  printf '<header><h1>%s</h1><p class="subtitle">Reproducible CI evidence generated by BaseHarbor.</p><div class="meta">' "$(printf '%s' "$title" | escape_html)"
  printf '<div><b>Phase</b><code>%s</code></div>' "$(printf '%s' "$phase" | escape_html)"
  printf '<div><b>Repository</b><code>%s</code></div>' "$(printf '%s' "${GITHUB_REPOSITORY:-unknown}" | escape_html)"
  printf '<div><b>Ref</b><code>%s</code></div>' "$(printf '%s' "$ref" | escape_html)"
  printf '<div><b>Commit</b><code>%s</code></div>' "$(printf '%s' "$sha" | escape_html)"
  printf '<div><b>Run</b><code>%s / attempt %s</code></div>' "$(printf '%s' "${GITHUB_RUN_ID:-unknown}" | escape_html)" "$(printf '%s' "${GITHUB_RUN_ATTEMPT:-1}" | escape_html)"
  printf '<div><b>Generated</b><code>%s</code></div>' "$(date -u +'%Y-%m-%dT%H:%M:%SZ' | escape_html)"
  printf '</div></header><section><table><thead><tr><th>Check</th><th>Result</th><th>Evidence</th></tr></thead><tbody>'
  if [ -n "$rows_file" ] && [ -f "$rows_file" ]; then
    while IFS=$'\t' read -r check status detail || [ -n "${check:-}" ]; do
      [ -n "${check:-}" ] || continue
      badge="$(status_badge "${status:-unknown}")"
      cls="unknown"
      case "$badge" in PASS) cls="pass";; FAIL) cls="fail";; SKIP) cls="skip";; CANCEL) cls="cancel";; esac
      printf '<tr><td>%s</td><td><span class="badge %s">%s</span></td><td>%s</td></tr>'         "$(printf '%s' "$check" | escape_html)" "$cls" "$(printf '%s' "$badge" | escape_html)" "$(printf '%s' "${detail:-}" | escape_html)"
    done < "$rows_file"
  fi
  printf '</tbody></table></section>'
  if [ -n "$run_url" ]; then
    printf '<footer>Run: <a href="%s">%s</a></footer>' "$(printf '%s' "$run_url" | escape_html)" "$(printf '%s' "$run_url" | escape_html)"
  fi
  printf '</main></body></html>\n'
} > "$out_dir/index.html"

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  cat "$out_dir/summary.md" >> "$GITHUB_STEP_SUMMARY"
fi
